[package]
name = "bulletproofs_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bulletproofs = "4.0.0"
curve25519-dalek-ng = "4.1.1"
merlin = "3.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
blake3 = "1.3.1"

